### ISSUE TITLE
CSS添砖加瓦

### ISSUE THREAD

**Issue by Hydraz320** [Hydraz320/Blog#3]
CSS时不时就成为我心头的伤

**Comment by Hydraz320** [comment]
先占坑 写写文本和图片的竖直对齐的问题

**Comment by Hydraz320** [comment]
# Flex

可以说，不考虑兼容性的情况下，Flex实在是一门利器。在网易的面试中，二面面试官竟然把我的Flex水平问了个底朝天(还好表现不错)。这里对Flex进行整理。

[参考：阮一峰的网络日志](http://www.ruanyifeng.com/blog/2015/07/flex-grammar.html)
[骰子案例](http://www.ruanyifeng.com/blog/2015/07/flex-examples.html)

## 容器属性

> * flex-direction(有时需要垂直方向来进行对齐处理)
> * flex-wrap
> * flex-flow(flex-direction属性和flex-wrap属性的简写)
> * justify-content(主轴对齐方式)
> * align-items(交叉轴对齐方式)
> * align-content

#### flex-direction
flex-direction属性决定主轴的方向（即项目的排列方向）。
```css
.box {
  flex-direction: row | row-reverse | column | column-reverse;
}
```
它可能有4个值。

> * row（默认值）：主轴为水平方向，起点在左端。
> * row-reverse：主轴为水平方向，起点在右端。
> * column：主轴为垂直方向，起点在上沿。
> * column-reverse：主轴为垂直方向，起点在下沿。

![flex-direction](https://github.com/Hydraz320/Blog/blob/master/images/CSS%E6%B7%BB%E7%A0%96%E5%8A%A0%E7%93%A6/bg2015071005.png?raw=true)

#### flex-wrap
flex-wrap属性定义，如果一条轴线排不下，如何换行。
```css
.box{
  flex-wrap: nowrap | wrap | wrap-reverse;
}
```
它可能取三个值。

(1) nowrap（默认）：不换行。
![nowrap](https://github.com/Hydraz320/Blog/blob/master/images/CSS%E6%B7%BB%E7%A0%96%E5%8A%A0%E7%93%A6/bg2015071007.png?raw=true)

(2) wrap：换行，第一行在上方。
![wrap](https://github.com/Hydraz320/Blog/blob/master/images/CSS%E6%B7%BB%E7%A0%96%E5%8A%A0%E7%93%A6/bg2015071008.jpg?raw=true)

(3) wrap-reverse：换行，第一行在下方。
![wrap-reverse](https://github.com/Hydraz320/Blog/blob/master/images/CSS%E6%B7%BB%E7%A0%96%E5%8A%A0%E7%93%A6/bg2015071009.jpg?raw=true)

#### flex-flow
flex-flow属性是flex-direction属性和flex-wrap属性的简写形式，默认值为row nowrap。
```css
.box {
  flex-flow: <flex-direction> || <flex-wrap>;
}
```
#### justify-content(主轴对齐方式)
justify-content属性定义了项目在主轴上的对齐方式。
```css
.box {
  justify-content: flex-start | flex-end | center | space-between | space-around;
}
```
![justify-content](https://github.com/Hydraz320/Blog/blob/master/images/CSS%E6%B7%BB%E7%A0%96%E5%8A%A0%E7%93%A6/bg2015071010.png?raw=true)

它可能取5个值，具体对齐方式与轴的方向有关。下面假设主轴为从左到右。

> * flex-start（默认值）：左对齐
> * flex-end：右对齐
> * **center： 居中（常用）**
> * space-between：两端对齐，项目之间的间隔都相等。
> * space-around：每个项目两侧的间隔相等。所以，项目之间的间隔比项目与边框的间隔大一倍。

#### align-items(交叉轴对齐方式)
align-items属性定义项目在交叉轴上如何对齐。
```css
.box {
  align-items: flex-start | flex-end | center | baseline | stretch;
}
```
![align-items](https://github.com/Hydraz320/Blog/blob/master/images/CSS%E6%B7%BB%E7%A0%96%E5%8A%A0%E7%93%A6/bg2015071011.png?raw=true)

它可能取5个值。具体的对齐方式与交叉轴的方向有关，下面假设交叉轴从上到下。

> * flex-start：交叉轴的起点对齐。
> * flex-end：交叉轴的终点对齐。
> * center：交叉轴的中点对齐。
> * baseline: 项目的第一行文字的基线对齐。
> * stretch（默认值）：如果项目未设置高度或设为auto，将占满整个容器的高度。

## align-content
align-content属性定义了多根轴线的对齐方式。如果项目只有一根轴线，该属性不起作用。
```css
.box {
  align-content: flex-start | flex-end | center | space-between | space-around | stretch;
}
```
![align-content](https://github.com/Hydraz320/Blog/blob/master/images/CSS%E6%B7%BB%E7%A0%96%E5%8A%A0%E7%93%A6/bg2015071012.png?raw=true)

该属性可能取6个值。

> * flex-start：与交叉轴的起点对齐。
> * flex-end：与交叉轴的终点对齐。
> * center：与交叉轴的中点对齐。
> * space-between：与交叉轴两端对齐，轴线之间的间隔平均分布。
> * space-around：每根轴线两侧的间隔都相等。所以，轴线之间的间隔比轴线与边框的间隔大一倍。
> * stretch（默认值）：轴线占满整个交叉轴。

## 项目属性
以下6个属性设置在项目上。

> * order(在圣杯布局中可以把nav提到左边)
> * flex-grow
> * flex-shrink
> * flex-basis
> * **flex(常用)**
> * align-self(可覆盖align-items交叉轴属性 配合css伪类选择器6的飞起 比如nth-child)

#### order
order属性定义项目的排列顺序。数值越小，排列越靠前，默认为0。
```css
.item {
  order: <integer>;
}
```
![order](https://github.com/Hydraz320/Blog/blob/master/images/CSS%E6%B7%BB%E7%A0%96%E5%8A%A0%E7%93%A6/bg2015071013.png?raw=true)
#### flex-grow
flex-grow属性定义项目的放大比例，默认为0，即如果存在剩余空间，也不放大。
```css
.item {
  flex-grow: <number>; /* default 0 */
}
```
![flex-grow](https://github.com/Hydraz320/Blog/blob/master/images/CSS%E6%B7%BB%E7%A0%96%E5%8A%A0%E7%93%A6/bg2015071014.png?raw=true)

如果所有项目的flex-grow属性都为1，则它们将等分剩余空间（如果有的话）。如果一个项目的flex-grow属性为2，其他项目都为1，则前者占据的剩余空间将比其他项多一倍。
#### flex-shrink
flex-shrink属性定义了项目的缩小比例，默认为1，即如果空间不足，该项目将缩小。
```css
.item {
  flex-shrink: <number>; /* default 1 */
}
```
![flex-shrink](https://github.com/Hydraz320/Blog/blob/master/images/CSS%E6%B7%BB%E7%A0%96%E5%8A%A0%E7%93%A6/bg2015071015.jpg?raw=true)

如果所有项目的flex-shrink属性都为1，当空间不足时，都将等比例缩小。如果一个项目的flex-shrink属性为0，其他项目都为1，则空间不足时，前者不缩小。
负值对该属性无效。

#### flex-basis
flex-basis属性定义了在分配多余空间之前，项目占据的主轴空间（main size）。浏览器根据这个属性，计算主轴是否有多余空间。它的默认值为auto，即项目的本来大小。
```css
.item {
  flex-basis: <length> | auto; /* default auto */
}
```
它可以设为跟width或height属性一样的值（比如350px），则项目将占据固定空间。
#### 5. flex(重要)**
flex属性是flex-grow, flex-shrink 和 flex-basis的简写，默认值为0 1 auto。后两个属性可选。

```css
.item {
  flex: none | [ <'flex-grow'> <'flex-shrink'>? || <'flex-basis'> ]
}
```
该属性有两个快捷值：auto (1 1 auto) 和 none (0 0 auto)。
建议优先使用这个属性，而不是单独写三个分离的属性，因为浏览器会推算相关值。

#### align-self
align-self属性允许单个项目有与其他项目不一样的对齐方式，可覆盖align-items属性。默认值为auto，表示继承父元素的align-items属性，如果没有父元素，则等同于stretch。
```css
.item {
  align-self: auto | flex-start | flex-end | center | baseline | stretch;
}
```
![align-self](https://github.com/Hydraz320/Blog/blob/master/images/CSS%E6%B7%BB%E7%A0%96%E5%8A%A0%E7%93%A6/bg2015071016.png?raw=true)

该属性可能取6个值，除了auto，其他都与align-items属性完全一致。

**Comment by Hydraz320** [comment]
# 居中

[参考 - CSS TRICKS](https://css-tricks.com/centering-css-complete-guide/)

---

# 水平居中
## inline/inline-*(文本或链接等)

```css
.center-children {
  text-align: center;
}
```
只要令想要居中的子元素(inline/inline-\*)的**父元素**的text-align为center即可。

## block

```css
.center-me {
  margin: 0 auto;
}
```
具有设置好的比父元素小width，即可通过margin来居中。如果width未设置即为100%，也就没有居中的意义了。

## 多个block
水平排列并居中
```css
/* 这里相当于居中的子元素从block变为inline-block再使用1.1的方法 */
.inline-block-center {
  text-align: center;
}
.inline-block-center div {
  display: inline-block;
  text-align: left;
}
/* 容器设为flex 主轴用justify-content对齐他 */ 
/* align-items控制交叉轴且默认stretch 所以居中元素会等高 */
.flex-center {
  display: flex;
  justify-content: center;
}
```
垂直排列并居中，就用margin: auto就好，注意要居中的子元素需要设置确定的宽度。

# 垂直居中
## inline/inline-*(文本或链接等)
### 单行(如单行短文字)
其中一个方法是设置上下padding相等。
```css
.link {
  padding-top: 30px;
  padding-bottom: 30px;
}
```
另一个方法则是在文本不会wrap的情况下，令行高与高度相等。
```css
.center-text-trick {
  height: 100px;
  line-height: 100px;
  white-space: nowrap;
}
```
### 多行

方法一：利用vertical-align: middle
在表格中，垂直居中是默认属性。因此对于非表格的情形下，也可以利用display来使其模仿table的性质(**两者的表现结果有差别！**)
```css
/* 容器转换为table */
.center-table {
  display: table;
  height: 250px;
  background: white;
  width: 240px;
  margin: 20px;
}
/* 子元素转化为table-cell，然后设置vertical-align: middle */
.center-table p {
  display: table-cell;
  margin: 0;
  background: black;
  color: white;
  padding: 20px;
  border: 10px solid white;
  vertical-align: middle;
}
```
方法二：flex走一个
对于flex方法而言，垂直居中和水平居中的区别只在于，flex-direction是垂直方向，居中依旧由justify-content来处理。**注意**不要混淆的一点是：align-items确实是定义项目在交叉轴上如何对齐，但子元素依旧是排列在水平方向是，它定义的是不同高度的子元素如何在水平方向上对齐(默认stretch)。参考下图：
![align-items](http://www.ruanyifeng.com/blogimg/asset/2015/bg2015071011.png)
```css
/* 和水平居中的区别就是flex-direction: column 非常漂亮 */
.flex-center-vertically {
  display: flex;
  justify-content: center;
  flex-direction: column;
  height: 400px;
}
```
**这种方法只适用于容器高度确定的情况！！！**

方法三：“Ghost element" 没怎么理解 先不管了。

## block
### 固定已知高度
```css
.parent {
  position: relative;
}
.child {
  position: absolute;
  top: 50%;
  height: 100px;
  margin-top: -50px;/* 高度的一半 */
}
```
注意**相对定位**。上述css代码是对于box-sizing: border-box的情形。对于box-sizing: content-box的情形，margin-top需要求取padding和border和的一半。
### 未知高度
```css
.parent {
  position: relative;
}
.child {
  position: absolute;
  top: 50%;
  transform: translateY(-50%);
}
```
注意使用transform: translateY(-50%)这一方法。transform属性允许我们对元素进行旋转、缩放、移动或倾斜。

### flexbox
flexbox的方法依旧容易，而且写法同inline/inline-*中flex写法。当然，容器高度依旧需要。
```css
.parent {
  display: flex;
  flex-direction: column;
  justify-content: center;
}
```
# 水平垂直居中
## 固定已知宽高
这一方法具有很好的跨平台兼容性。就是用负margin的技巧。
```css
.parent {
  position: relative;
}

.child {
  width: 300px;
  height: 100px;
  padding: 20px;

  position: absolute;
  top: 50%;
  left: 50%;

  margin: -70px 0 0 -170px;
}
```
## 未知宽高
已知用margin，未知用transform：translate，它基于当前元素的width和height来自动调整。
```css
.parent {
  position: relative;
}
.child {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
```
## flexbox
把主轴的justify-content和交叉轴的align-items都center了就ok了。
```css
.parent {
  display: flex;
  justify-content: center;
  align-items: center;
}
```

# 浮动水平垂直居中

撇去float的破坏性，float就是个带方向的inline-block。注意要relative定位才行(至于为什么relative...因为absolute是相对于第一个不为static的父元素定位的，而这段代码的container就是static呀。所以最后会相对于页面的主体来定位...)。

```css
#container {
  width: 960px;
  height: 200px;
  background-color: red;
}
#box {
  float: left;
  position: relative;
  left: 50%;
  top: 50%;
  transform: translate(-50%, -50%);
  width: 100px;
  height: 100px;
  background-color: yellow;
}
```
